rest_api:
    resource: "@RestApiBundle/Controller/"
    type:     annotation
    prefix:   /

users_v1:
    resource: RestApi\Bundle\Controller\UsersController
    type: rest
    prefix: /v1
    name_prefix: v1_

users_v2:
    resource: RestApi\Bundle\Controller\UsersControllerV2
    type: rest
    prefix: /v2
    name_prefix: v2_

app:
    resource: @AppBundle/Controller/
    type:     annotation
