rest_api:
    resource: "@RestApiBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type:     rest
    resource: RestApi\Bundle\Controller\UsersController

app:
    resource: @AppBundle/Controller/
    type:     annotation
